### PR TITLE
pypdf 3.2.1, add `noarch: python`, maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for maintaining this! 

References:
- includes #3
- obviates the need for #1 and #2 
  - ... and the inevitable `aarch`, `osx-arm64` and whatever future migration PRs

Notes:
- makes this `noarch: python`
  - the only python-sensitive packages are (essentially) no-op, empty packages in `conda-forge` for the
- updates some metadata (`docs_url`, etc)
- adds self as maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge/pypdf ready for review :scroll:

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/core please consider merging this PR which adds a maintainer and unblocks use of this on more pythons

**Comment by bollwyvl** [comment]
:laughing: #5

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
